trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'mishri' 
    repository: 'exampledockerimage'
    command: 'buildAndPush'
    Dockerfile: '/Dockerfile'
    tags: '$(Build.BuildId)'

- task: AzureCLI@2
  inputs:
    azureSubscription: '1c6bc2a3-8cad-44df-a1cd-92202930946a'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --resource-group example-resources --name exampleaks --overwrite-existing

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'YourKubernetesServiceConnection'
    namespace: 'test'
    manifests: '/*.yaml'